"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const crypto_controller_1 = require("../controllers/crypto.controller");
const router = express_1.default.Router();
router.post('/', crypto_controller_1.createCrypto);
router.put('/symbol/:symbol', crypto_controller_1.updateCryptoBySymbol);
router.put('/id/:id', crypto_controller_1.updateCryptoById);
router.delete('/:symbol', crypto_controller_1.deleteCrypto);
router.post('/:symbol/price', crypto_controller_1.updateCryptoPrice);
router.post('/:symbol/history', crypto_controller_1.addCryptoHistory);
router.get('/', crypto_controller_1.getAllCryptos);
router.get('/symbol/:symbol', crypto_controller_1.getCryptoBySymbol);
router.get('/id/:id', crypto_controller_1.getCryptoById);
router.get('/:symbol/history', crypto_controller_1.getCryptoHistory);
router.post('/coingainers', crypto_controller_1.createCoinGainer);
router.post('/coingainers/bulk', crypto_controller_1.bulkUpdateCoinGainers);
router.get('/coingainers', crypto_controller_1.getAllCoinGainers);
router.get('/coingainers/top', crypto_controller_1.getTopGainers);
router.get('/coingainers/losers', crypto_controller_1.getTopLosers);
router.get('/coingainers/:symbol', crypto_controller_1.getCoinGainer);
router.post('/coinlosers', crypto_controller_1.createCoinLoser);
router.post('/coinlosers/bulk', crypto_controller_1.bulkUpdateCoinLosers);
router.post('/coinlosers/sync', crypto_controller_1.syncCoinLosers);
router.get('/coinlosers', crypto_controller_1.getAllCoinLosers);
router.get('/coinlosers/top', crypto_controller_1.getTopLosers);
router.get('/coinlosers/:symbol', crypto_controller_1.getCoinLoser);
router.put('/coinlosers/:symbol', crypto_controller_1.updateCoinLoser);
router.delete('/coinlosers/:symbol', crypto_controller_1.deleteCoinLoser);
router.post('/coin-history', crypto_controller_1.createCoinHistory);
router.get('/coin-history', crypto_controller_1.getAllCoinHistories);
router.get('/coin-history/:symbol', crypto_controller_1.getCoinHistory);
router.get('/coin-history/:symbol/stats', crypto_controller_1.getCoinHistoryStats);
router.delete('/coin-history/:id', crypto_controller_1.deleteCoinHistory);
router.get('/:symbol/comprehensive', crypto_controller_1.getComprehensiveData);
router.post('/crypto/bulk/upsert', crypto_controller_1.bulkUpsertCryptos);
exports.default = router;
//# sourceMappingURL=crypto.routes.js.map