"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const stocks_controller_1 = require("../controllers/stocks.controller");
const router = express_1.default.Router();
router.post('/equity/profiles', stocks_controller_1.createProfile);
router.get('/equity/profiles/:company_id', stocks_controller_1.getProfileByCompanyId);
router.put('/equity/profiles/:company_id', stocks_controller_1.updateProfile);
router.delete('/equity/profiles/:company_id', stocks_controller_1.deleteProfile);
router.post('/equity/statistics', stocks_controller_1.createStatistics);
router.get('/equity/statistics/:company_id', stocks_controller_1.getStatisticsByCompanyId);
router.put('/equity/statistics/:company_id', stocks_controller_1.updateStatistics);
router.delete('/equity/statistics/:company_id', stocks_controller_1.deleteStatistics);
router.post('/equity/dividends', stocks_controller_1.createDividends);
router.get('/equity/dividends/:company_id', stocks_controller_1.getDividendsByCompanyId);
router.put('/equity/dividends/:company_id', stocks_controller_1.updateDividends);
router.delete('/equity/dividends/:company_id', stocks_controller_1.deleteDividends);
router.post('/equity/earnings', stocks_controller_1.createEarnings);
router.get('/equity/earnings/:company_id', stocks_controller_1.getEarningsByCompanyId);
router.put('/equity/earnings/:company_id', stocks_controller_1.updateEarnings);
router.delete('/equity/earnings/:company_id', stocks_controller_1.deleteEarnings);
router.post('/equity/financial', stocks_controller_1.createFinancial);
router.get('/equity/financial/:company_id', stocks_controller_1.getFinancialByCompanyId);
router.put('/equity/financial/:company_id', stocks_controller_1.updateFinancial);
router.delete('/equity/financial/:company_id', stocks_controller_1.deleteFinancial);
router.post('/equity/holders', stocks_controller_1.createHolders);
router.get('/equity/holders/:company_id', stocks_controller_1.getHoldersByCompanyId);
router.put('/equity/holders/:company_id', stocks_controller_1.updateHolders);
router.delete('/equity/holders/:company_id', stocks_controller_1.deleteHolders);
router.post('/equity/price-history', stocks_controller_1.createPriceHistory);
router.get('/equity/price-history/:company_id', stocks_controller_1.getCompanyPriceHistory);
router.put('/equity/price-history/:company_id', stocks_controller_1.updatePriceHistory);
router.delete('/equity/price-history/:company_id', stocks_controller_1.deletePriceHistory);
router.get('/equity/price-history/:company_id/24h', stocks_controller_1.getCompanyPriceHistoryByLast24Hours);
router.get('/equity/price-history/:company_id/1w', stocks_controller_1.getCompanyPriceHistoryByLast1Week);
router.get('/equity/price-history/:company_id/3m', stocks_controller_1.getCompanyPriceHistoryByLast3Months);
router.get('/equity/price-history/:company_id/6m', stocks_controller_1.getCompanyPriceHistoryByLast6Months);
router.get('/equity/price-history/:company_id/ytd', stocks_controller_1.getCompanyPriceHistoryByYearToDate);
router.get('/equity/price-history/:company_id/1y', stocks_controller_1.getCompanyPriceHistoryByLast1Year);
router.get('/equity/price-history/:company_id/2y', stocks_controller_1.getCompanyPriceHistoryByLast2Years);
router.get('/equity/price-history/:company_id/5y', stocks_controller_1.getCompanyPriceHistoryByLast5Years);
router.get('/equity/price-history/:company_id/10y', stocks_controller_1.getCompanyPriceHistoryByLast10Years);
router.get('/equity/price-history/:company_id/all', stocks_controller_1.getCompanyAllTimePriceHistory);
router.post('/equity/price-history/:company_id/entries', stocks_controller_1.addPriceEntry);
router.put('/equity/price-history/:company_id/latest', stocks_controller_1.updateLatestPrice);
router.get('/equity/exchange/:exchangeSymbol/top-gainers', stocks_controller_1.getTopGainersByExchange);
router.get('/equity/exchange/:exchangeSymbol/top-losers', stocks_controller_1.getTopLosersByExchange);
router.get('/equity/exchange/:exchangeSymbol/performance-by-industry', stocks_controller_1.getPerformanceByIndustry);
router.get('/equity/exchange/:exchangeSymbol/market-movers', stocks_controller_1.getMarketMoversByExchange);
router.get('/equity/company/:company_id/all', stocks_controller_1.getCompanyAllData);
router.get('/equity/gse/status', stocks_controller_1.getGSEMarketStatus);
router.post('/equity/gse/status/update', stocks_controller_1.manualGSEStatusUpdate);
router.post('/equity/bulk/profiles', stocks_controller_1.bulkCreateProfiles);
router.put('/equity/bulk/profiles', stocks_controller_1.bulkUpdateProfiles);
router.post('/equity/bulk/statistics', stocks_controller_1.bulkCreateStatistics);
router.put('/equity/bulk/statistics', stocks_controller_1.bulkUpdateStatistics);
router.post('/equity/bulk/price-history', stocks_controller_1.bulkCreatePriceHistory);
router.post('/equity/bulk/price-history/entries', stocks_controller_1.bulkAddPriceEntries);
router.post('/equity/bulk/upsert', stocks_controller_1.bulkUpsertCollection);
router.delete('/equity/bulk/companies', stocks_controller_1.bulkDeleteCompanies);
router.post('/equity/bulk/import', stocks_controller_1.bulkImportCompanies);
exports.default = router;
//# sourceMappingURL=stocks.routes.js.map